/**
 * @fileoverview PDF Specification Sheet Generator for FurnAI
 *
 * Generates professional production specification PDFs using pdfmake.
 * These spec sheets are factory-ready and include:
 *   - FurnAI branded header
 *   - Order / design info
 *   - Component breakdown table
 *   - Hardware list
 *   - Material summary
 *   - Assembly notes
 *
 * @module lib/export/pdfSpec
 */

import pdfMake from "pdfmake";
import { join } from "path";

/**
 * Embedded font descriptors for pdfmake (server-side TTF paths).
 */
const fonts = {
  Roboto: {
    normal: join(process.cwd(), "node_modules/pdfmake/fonts/Roboto/Roboto-Regular.ttf"),
    bold: join(process.cwd(), "node_modules/pdfmake/fonts/Roboto/Roboto-Medium.ttf"),
    italics: join(process.cwd(), "node_modules/pdfmake/fonts/Roboto/Roboto-Italic.ttf"),
    bolditalics: join(process.cwd(), "node_modules/pdfmake/fonts/Roboto/Roboto-MediumItalic.ttf"),
  },
};

/**
 * Generates a production specification PDF.
 *
 * @param {object} params
 * @param {object} params.design        — Design metadata (name, type, style, etc.)
 * @param {Array<{ name: string, width: number, height: number, thickness: number, quantity?: number, material?: string }>} params.panels
 *   Component/panel breakdown.
 * @param {object} [params.materials]   — Material specifications.
 * @param {Array<{ item: string, quantity: number, specification?: string }>} [params.hardware]
 *   Hardware list.
 * @param {object} [params.dimensions]  — Overall dimensions { width, height, depth }.
 * @param {string} [params.orderNumber] — Order reference number.
 * @param {string[]} [params.assemblyNotes] — Assembly instruction steps.
 * @returns {Promise<Buffer>} PDF file as a Node.js Buffer.
 *
 * @example
 *   const pdfBuffer = await generateSpecSheet({
 *     design: { name: "Modern Wardrobe", type: "wardrobe", style: "modern" },
 *     panels: [{ name: "Side Panel", width: 600, height: 2200, thickness: 18, quantity: 2 }],
 *     orderNumber: "FURNI-1234",
 *   });
 */
export async function generateSpecSheet({
  design,
  panels = [],
  materials = {},
  hardware = [],
  dimensions = {},
  orderNumber,
  assemblyNotes = [],
}) {
  const docDefinition = buildDocDefinition({
    design,
    panels,
    materials,
    hardware,
    dimensions,
    orderNumber,
    assemblyNotes,
  });

  try {
    pdfMake.setFonts(fonts);
    const pdfDoc = pdfMake.createPdf(docDefinition);
    return await pdfDoc.getBuffer();
  } catch (err) {
    throw new Error(`PDF generation failed: ${err.message}`);
  }
}

/**
 * Builds the pdfmake document definition object.
 *
 * @param {object} params — Same params as generateSpecSheet.
 * @returns {object} pdfmake document definition.
 * @private
 */
function buildDocDefinition({
  design,
  panels,
  materials,
  hardware,
  dimensions,
  orderNumber,
  assemblyNotes,
}) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const designName = design?.name || "Untitled Design";
  const designType = design?.type || "furniture";
  const designStyle = design?.style || "modern";

  return {
    pageSize: "A4",
    pageMargins: [40, 60, 40, 50],

    // ── Header ─────────────────────────────────────────────────────
    header: {
      columns: [
        {
          text: "FURNAI",
          style: "brandHeader",
          margin: [40, 15, 0, 0],
        },
        {
          text: "Production Specification",
          style: "headerSubtitle",
          alignment: "right",
          margin: [0, 20, 40, 0],
        },
      ],
    },

    // ── Footer ─────────────────────────────────────────────────────
    footer: (currentPage, pageCount) => ({
      columns: [
        {
          text: `Generated by FurnAI — ${dateStr}`,
          alignment: "left",
          style: "footerText",
          margin: [40, 0, 0, 0],
        },
        {
          text: `Page ${currentPage} of ${pageCount}`,
          alignment: "right",
          style: "footerText",
          margin: [0, 0, 40, 0],
        },
      ],
    }),

    // ── Content ────────────────────────────────────────────────────
    content: [
      // Title block
      {
        table: {
          widths: ["*"],
          body: [
            [
              {
                text: designName.toUpperCase(),
                style: "title",
                fillColor: "#1a1a2e",
                color: "#ffffff",
                margin: [10, 8, 10, 4],
              },
            ],
          ],
        },
        layout: "noBorders",
        margin: [0, 0, 0, 10],
      },

      // Order info row
      {
        columns: [
          { text: `Order: ${orderNumber || "N/A"}`, style: "infoLabel" },
          { text: `Type: ${designType}`, style: "infoLabel" },
          { text: `Style: ${designStyle}`, style: "infoLabel" },
          { text: `Date: ${dateStr}`, style: "infoLabel" },
        ],
        margin: [0, 0, 0, 12],
      },

      // ── Overall Dimensions ─────────────────────────────────────
      ...(dimensions.width || dimensions.height || dimensions.depth
        ? [
            { text: "OVERALL DIMENSIONS", style: "sectionHeader" },
            {
              table: {
                widths: ["*", "*", "*"],
                body: [
                  [
                    { text: "Width", style: "dimLabel" },
                    { text: "Height", style: "dimLabel" },
                    { text: "Depth", style: "dimLabel" },
                  ],
                  [
                    { text: `${dimensions.width || "—"} mm`, style: "dimValue" },
                    { text: `${dimensions.height || "—"} mm`, style: "dimValue" },
                    { text: `${dimensions.depth || "—"} mm`, style: "dimValue" },
                  ],
                ],
              },
              layout: "lightHorizontalLines",
              margin: [0, 0, 0, 12],
            },
          ]
        : []),

      // ── Materials ──────────────────────────────────────────────
      ...(materials && Object.keys(materials).length > 0
        ? [
            { text: "MATERIALS", style: "sectionHeader" },
            {
              ul: Object.entries(materials).map(
                ([key, val]) => `${key}: ${val}`
              ),
              style: "listItem",
              margin: [0, 0, 0, 12],
            },
          ]
        : []),

      // ── Component Breakdown ────────────────────────────────────
      { text: "COMPONENT BREAKDOWN", style: "sectionHeader" },
      panels.length > 0
        ? {
            table: {
              headerRows: 1,
              widths: ["*", 55, 55, 45, 30, 70],
              body: [
                [
                  { text: "Component", style: "tableHeader" },
                  { text: "Width", style: "tableHeader" },
                  { text: "Height", style: "tableHeader" },
                  { text: "Thick.", style: "tableHeader" },
                  { text: "Qty", style: "tableHeader" },
                  { text: "Material", style: "tableHeader" },
                ],
                ...panels.map((p) => [
                  { text: p.name || "—", style: "tableCell" },
                  { text: `${p.width || "—"}`, style: "tableCellNum" },
                  { text: `${p.height || "—"}`, style: "tableCellNum" },
                  { text: `${p.thickness || "—"}`, style: "tableCellNum" },
                  { text: `${p.quantity || 1}`, style: "tableCellNum" },
                  { text: p.material || "—", style: "tableCell" },
                ]),
              ],
            },
            layout: {
              hLineWidth: () => 0.5,
              vLineWidth: () => 0,
              hLineColor: () => "#cccccc",
              paddingTop: () => 4,
              paddingBottom: () => 4,
              fillColor: (rowIndex) =>
                rowIndex === 0 ? "#f0f0f5" : rowIndex % 2 === 0 ? "#fafafa" : null,
            },
            margin: [0, 0, 0, 12],
          }
        : { text: "No panels specified.", italics: true, margin: [0, 0, 0, 12] },

      // ── Hardware List ──────────────────────────────────────────
      ...(hardware.length > 0
        ? [
            { text: "HARDWARE LIST", style: "sectionHeader" },
            {
              table: {
                headerRows: 1,
                widths: ["*", 50, "*"],
                body: [
                  [
                    { text: "Item", style: "tableHeader" },
                    { text: "Qty", style: "tableHeader" },
                    { text: "Specification", style: "tableHeader" },
                  ],
                  ...hardware.map((hw) => [
                    { text: hw.item || hw.description || "—", style: "tableCell" },
                    { text: `${hw.quantity || "—"}`, style: "tableCellNum" },
                    {
                      text: hw.specification || hw.partNumber || "—",
                      style: "tableCell",
                    },
                  ]),
                ],
              },
              layout: {
                hLineWidth: () => 0.5,
                vLineWidth: () => 0,
                hLineColor: () => "#cccccc",
                paddingTop: () => 4,
                paddingBottom: () => 4,
                fillColor: (rowIndex) =>
                  rowIndex === 0 ? "#f0f0f5" : null,
              },
              margin: [0, 0, 0, 12],
            },
          ]
        : []),

      // ── Assembly Notes ─────────────────────────────────────────
      ...(assemblyNotes.length > 0
        ? [
            { text: "ASSEMBLY NOTES", style: "sectionHeader" },
            {
              ol: assemblyNotes,
              style: "listItem",
              margin: [0, 0, 0, 12],
            },
          ]
        : []),

      // ── Quality checklist ──────────────────────────────────────
      { text: "QUALITY CHECKLIST", style: "sectionHeader" },
      {
        ul: [
          "Verify all dimensions within ±1mm tolerance",
          "Check all edges for chips or defects",
          "Test all moving parts for smooth operation",
          "Verify color consistency across all panels",
          "Confirm hardware count matches specification",
        ],
        style: "listItem",
        margin: [0, 0, 0, 12],
      },
    ],

    // ── Styles ─────────────────────────────────────────────────────
    styles: {
      brandHeader: {
        fontSize: 18,
        bold: true,
        color: "#1a1a2e",
        font: "Roboto",
      },
      headerSubtitle: {
        fontSize: 10,
        color: "#666666",
      },
      title: {
        fontSize: 16,
        bold: true,
      },
      sectionHeader: {
        fontSize: 11,
        bold: true,
        color: "#1a1a2e",
        margin: [0, 8, 0, 6],
        decoration: "underline",
        decorationColor: "#1a1a2e",
      },
      infoLabel: {
        fontSize: 9,
        color: "#444444",
      },
      dimLabel: {
        fontSize: 9,
        color: "#888888",
        alignment: "center",
      },
      dimValue: {
        fontSize: 12,
        bold: true,
        alignment: "center",
      },
      tableHeader: {
        fontSize: 8,
        bold: true,
        color: "#333333",
      },
      tableCell: {
        fontSize: 8,
      },
      tableCellNum: {
        fontSize: 8,
        alignment: "center",
      },
      listItem: {
        fontSize: 9,
        lineHeight: 1.4,
      },
      footerText: {
        fontSize: 7,
        color: "#aaaaaa",
      },
    },

    defaultStyle: {
      font: "Roboto",
      fontSize: 9,
    },
  };
}
